// permissions.js
// Centralized permission scopes and role associations

const PERMISSIONS = {
  // Appointments
  APPOINTMENT_READ: 'APPOINTMENT_READ',
  APPOINTMENT_WRITE: 'APPOINTMENT_WRITE',
  APPOINTMENT_MANAGE: 'APPOINTMENT_MANAGE', // managing doctors and hospitals

  // Audit logs
  AUDIT_READ: 'AUDIT_READ',
  AUDIT_MANAGE: 'AUDIT_MANAGE',

  // FinOps
  FINOPS_READ: 'FINOPS_READ',
  FINOPS_MANAGE: 'FINOPS_MANAGE',

  // Users management
  USER_READ: 'USER_READ',
  USER_WRITE: 'USER_WRITE',
  USER_MANAGE: 'USER_MANAGE',

  // Notification preferences and logs
  NOTIFICATION_READ: 'NOTIFICATION_READ',
  NOTIFICATION_MANAGE: 'NOTIFICATION_MANAGE',

  // Health
  HEALTH_READ: 'HEALTH_READ',
  HEALTH_WRITE: 'HEALTH_WRITE',
  HEALTH_DOCUMENT_READ: 'HEALTH_DOCUMENT_READ',
  HEALTH_DOCUMENT_WRITE: 'HEALTH_DOCUMENT_WRITE',

  // Notes
  NOTES_READ: 'NOTES_READ',
  NOTES_WRITE: 'NOTES_WRITE',

  // Reminders
  REMINDER_READ: 'REMINDER_READ',
  REMINDER_WRITE: 'REMINDER_WRITE',

  // Alerts
  ALERT_READ: 'ALERT_READ',
  ALERT_WRITE: 'ALERT_WRITE',
  ALERT_MANAGE: 'ALERT_MANAGE',

  // Reports
  REPORT_READ: 'REPORT_READ',
  REPORT_GENERATE: 'REPORT_GENERATE',

  // AI
  AI_READ: 'AI_READ',
  AI_EXECUTE: 'AI_EXECUTE'
};

// Roles: SUPER_ADMIN, ADMIN, CAREGIVER, USER
const ROLE_PERMISSIONS = {
  SUPER_ADMIN: [
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.APPOINTMENT_WRITE,
    PERMISSIONS.APPOINTMENT_MANAGE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.AUDIT_MANAGE,
    PERMISSIONS.FINOPS_READ,
    PERMISSIONS.FINOPS_MANAGE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_WRITE,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.NOTIFICATION_MANAGE,
    PERMISSIONS.HEALTH_READ,
    PERMISSIONS.HEALTH_WRITE,
    PERMISSIONS.HEALTH_DOCUMENT_READ,
    PERMISSIONS.HEALTH_DOCUMENT_WRITE,
    PERMISSIONS.NOTES_READ,
    PERMISSIONS.NOTES_WRITE,
    PERMISSIONS.REMINDER_READ,
    PERMISSIONS.REMINDER_WRITE,
    PERMISSIONS.ALERT_READ,
    PERMISSIONS.ALERT_WRITE,
    PERMISSIONS.ALERT_MANAGE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_GENERATE,
    PERMISSIONS.AI_READ,
    PERMISSIONS.AI_EXECUTE
  ],
  ADMIN: [
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.APPOINTMENT_WRITE,
    PERMISSIONS.APPOINTMENT_MANAGE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.FINOPS_READ,
    PERMISSIONS.FINOPS_MANAGE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_WRITE,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.NOTIFICATION_MANAGE,
    PERMISSIONS.HEALTH_READ,
    PERMISSIONS.HEALTH_WRITE,
    PERMISSIONS.HEALTH_DOCUMENT_READ,
    PERMISSIONS.HEALTH_DOCUMENT_WRITE,
    PERMISSIONS.NOTES_READ,
    PERMISSIONS.NOTES_WRITE,
    PERMISSIONS.REMINDER_READ,
    PERMISSIONS.REMINDER_WRITE,
    PERMISSIONS.ALERT_READ,
    PERMISSIONS.ALERT_WRITE,
    PERMISSIONS.ALERT_MANAGE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_GENERATE,
    PERMISSIONS.AI_READ,
    PERMISSIONS.AI_EXECUTE
  ],
  CAREGIVER: [
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.APPOINTMENT_WRITE,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.HEALTH_READ,
    PERMISSIONS.HEALTH_WRITE,
    PERMISSIONS.HEALTH_DOCUMENT_READ,
    PERMISSIONS.HEALTH_DOCUMENT_WRITE,
    PERMISSIONS.NOTES_READ,
    PERMISSIONS.NOTES_WRITE,
    PERMISSIONS.REMINDER_READ,
    PERMISSIONS.REMINDER_WRITE,
    PERMISSIONS.ALERT_READ,
    PERMISSIONS.ALERT_WRITE,
    PERMISSIONS.ALERT_MANAGE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_GENERATE,
    PERMISSIONS.AI_EXECUTE
  ],
  USER: [
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.APPOINTMENT_WRITE,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.HEALTH_READ,
    PERMISSIONS.HEALTH_WRITE,
    PERMISSIONS.HEALTH_DOCUMENT_READ,
    PERMISSIONS.HEALTH_DOCUMENT_WRITE,
    PERMISSIONS.NOTES_READ,
    PERMISSIONS.REMINDER_READ,
    PERMISSIONS.REMINDER_WRITE,
    PERMISSIONS.ALERT_READ,
    PERMISSIONS.ALERT_WRITE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.AI_EXECUTE
  ]
};

module.exports = {
  PERMISSIONS,
  ROLE_PERMISSIONS
};

