name: CI Pipeline

on:
  push:
    branches: [ main, develop, feature/test ]
  pull_request:

jobs:
  ci:
    uses: AWS-Elderping/elderping-github-templates/.github/workflows/ci-reusable.yaml@main
    with:
      service_name: "report-service"
      ecr_repository: "elderpinq-dev-report-service"
    secrets: inherit

